// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt1LZMQE0mXF8cCUUIJ1C2HHA6Pz35zW0',
    appId: '1:512276744817:web:f37f2a89e76c88744a69d0',
    messagingSenderId: '512276744817',
    projectId: 'norexstore-27017',
    authDomain: 'norexstore-27017.firebaseapp.com',
    storageBucket: 'norexstore-27017.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLBfSMLL4CUVrVPIhOqFLSFgHEiy11520',
    appId: '1:512276744817:android:527d910bb52a82324a69d0',
    messagingSenderId: '512276744817',
    projectId: 'norexstore-27017',
    storageBucket: 'norexstore-27017.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF1uwDTx9LnnXIiqFIlu7HxWHBdxNBhaE',
    appId: '1:512276744817:ios:268521f15c5aa3674a69d0',
    messagingSenderId: '512276744817',
    projectId: 'norexstore-27017',
    storageBucket: 'norexstore-27017.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF1uwDTx9LnnXIiqFIlu7HxWHBdxNBhaE',
    appId: '1:512276744817:ios:268521f15c5aa3674a69d0',
    messagingSenderId: '512276744817',
    projectId: 'norexstore-27017',
    storageBucket: 'norexstore-27017.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
